# These are supported funding model platforms
github: tijuks
patreon: tijuks
community_bridge: tijuks
liberapay: tijuks 
issuehunt: tijuks
lfx_crowdfunding: # Reg., cloud-foundry
polar: tijuks
buy_me_a_coffee: tijuks
thanks_dev:  tijuks
custom: https://global.info-systems.com/donate/tijuks
