# These are supported funding model platforms
github: #tijuks
patreon: #Tijuks
open_collective: #tijuks
ko_fi: #tijuks
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Reg., cloud-foundry
polar: #tijuks
buy_me_a_coffee: #tijuks
thanks_dev: # tijuks
custom: #tijuks
